# =============== Project Configuration ===============
language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-26.0.2
    - android-26
    - extra-android-m2repository
    
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'


# =============== VM configuration ===============
jdk:
    - oraclejdk8

sudo: false


# =============== Before ===============
before_install:
    - chmod +x gradlew


# =============== Running ===============
script:
    - ./gradlew :clean :spitfire:build


# =============== After ===============
after_success:
    - ./gradlew :spitfire:cobertura :spitfire:coveralls
    - ./gradlew :spitfire:bintrayUpload